<?php
# This file was automatically generated by the MediaWiki 1.39.11
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "KnowledgeBase";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://localhost:8080";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "postgres";
$wgDBserver = "postgres-mediawiki";
$wgDBname = "mediawiki";
$wgDBuser = "wikiuser";
$wgDBpassword = "wikipass";

# Postgres specific settings
$wgDBport = "5432";
$wgDBmwschema = "mediawiki";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "72fd534676b218bebaa17da1ae5c825d8a0ffbabebb5a6b534516ac7843a102f";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a68daef5124c869f";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://www.gnu.org/copyleft/fdl.html";
$wgRightsText = "GNU Free Documentation License 1.3 or later";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/gnu-fdl.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions["*"]["edit"] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "timeless";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

$wgShowExceptionDetails = true;
$wgSupportSystemRedmineAPIKey = '84a82c13bc045473b38f31835bfe17cee7bf9c0d';
$wgSupportSystemRedmineURL = getenv('REDMINE_URL') ?: 'http://redmine:3000';
$wgSupportSystemGraphDataFile = '/var/www/html/extensions/SupportSystem/data/graph_data.json';

$wgSearchType = 'CirrusSearch';
$wgCirrusSearchServers = [
	'http://opensearch-node1:9200',
	'http://opensearch-node2:9200'
];

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'AdvancedSearch' );
wfLoadExtension( 'CirrusSearch' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'Elastica' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'SupportSystem' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TimedMediaHandler' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension('Validator');
wfLoadExtension('SemanticMediaWiki');
enableSemantics('localhost:8080');
$smwgPageSpecialProperties[] = '_MDAT';
$smwgPageSpecialProperties[] = '_CDAT';
$smwgPageSpecialProperties[] = '_NEWP';
$smwgPageSpecialProperties[] = '_LEDT';
$smwgQMaxInlineLimit = 500;
$smwgQMaxLimit = 10000;
$smwgQMaxSize = 100;
$smwgQMaxDepth = 10;
wfLoadExtension('SemanticResultFormats');
wfLoadExtension('SemanticDrilldown');
wfLoadExtension('SemanticWatchlist');
wfLoadExtension('SemanticTasks');
wfLoadExtension('SemanticCite');
wfLoadExtension('SemanticGlossary');

# ===== LDAP РАСШИРЕНИЯ (ДЛЯ БУДУЩЕГО ИСПОЛЬЗОВАНИЯ) =====
# PluggableAuth - базовое расширение для LDAP
#wfLoadExtension('PluggableAuth');
#$wgPluggableAuth_EnableAutoLogin = false;
#$wgPluggableAuth_EnableLocalLogin = true;
# LDAPProvider - базовый провайдер LDAP
#wfLoadExtension('LDAPProvider');
# LDAPAuthentication2
#wfLoadExtension('LDAPAuthentication2');
# LDAPAuthorization
#wfLoadExtension('LDAPAuthorization');
# LDAPGroups
#wfLoadExtension('LDAPGroups');
# LDAPUserInfo
#wfLoadExtension('LDAPUserInfo');
# LDAPSyncAll
#wfLoadExtension('LDAPSyncAll');
# Конфигурация LDAP (закомментирована для локальной разработки)
#$LDAPProviderDomainConfigProvider = function() {
#    $config = [
#        'example.com' => [
#            'connection' => [
#                'server' => 'ldap.example.com',
#                'port' => 389,
#                'enctype' => 'clear',
#                'options' => [
#                    'LDAP_OPT_DEREF' => 1
#                ],
#                'basedn' => 'dc=example,dc=com',
#                'userbasedn' => 'ou=users,dc=example,dc=com',
#                'groupbasedn' => 'ou=groups,dc=example,dc=com',
#                'searchattribute' => 'uid',
#                'usernameattribute' => 'uid',
#                'realnameattribute' => 'cn',
#                'emailattribute' => 'mail',
#            ]
#        ]
#    ];
#    return new \MediaWiki\Extension\LDAPProvider\DomainConfigProvider\InlinePHPArray( $config );
#};

# ===== РАСШИРЕНИЯ ОТ LVEFUNC =====
wfLoadExtension('MiniORM');
wfLoadExtension('Workflows');
wfLoadExtension('Review');

wfLoadExtension('CodeMirror');
$wgDefaultUserOptions['usecodemirror'] = 1;
wfLoadExtension('CategoryTree');
wfLoadExtension('InputBox');
wfLoadExtension('PageForms');
wfLoadExtension('EmbedVideo');

# ===== ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ =====
$wgMaxArticleSize = 2048;
$wgFileExtensions = [
	'png',
	'gif',
	'jpg',
	'jpeg',
	'pdf',
	'doc',
	'docx',
	'xls',
	'xlsx',
	'ppt',
	'pptx',
	'odt',
	'ods',
	'odp',
	'odg',
	'mp4',
	'webm',
	'ogv',
	'mp3',
	'ogg',
	'wav'
];
$wgUploadSizeWarning = 100 * 1024 * 1024; # 100MB
$wgMaxUploadSize = 100 * 1024 * 1024; # 100MB
$wgJobRunRate = 0.01;
$wgResourceLoaderMaxage = [
	'versioned' => 30 * 24 * 60 * 60, // 30 days
	'unversioned' => 5 * 60 // 5 minutes
];
$wgShowExceptionDetails = true;
$wgDebugToolbar = true;
$wgShowDebug = false;
$wgDevelopmentWarnings = true;

# End of automatically generated settings.
# Add more configuration options below.
